language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby
  - rbx
after_script:
  - bundle exec rake coveralls:push
matrix:
  fast_finish: true
  allow_failures:
    - rvm: rbx
    - rvm: ruby-head
